import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { CartProvider } from "../context/CartContext";
import { CartSlider } from "./components/CartSlider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body>
        <CartProvider>
          <Header />
          {children}
          <CartSlider />
          <Footer />
        </CartProvider>
      </body>
    </html>
  )
}
